datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.1
micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        descriptions: true
        step: PT1M
jpa.default.properties.hibernate.hbm2ddl.auto: update
